---

collections:
  - name: amazon.aws
    version: 6.4.0

roles:
  - src: grog.package
    version: v1.3.0
  - src: https://github.com/patrickjahns/ansible-role-promtail
    version: 1.27.0
    name: patrickjahns.promtail
